esphome:
  name: example_sfd_vosloh
  friendly_name: Example SFD vosloh

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  source: github://chrissileinus/ESPHomeComponent

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "example_sfd_vosloh"

captive_portal:

# Example configuration entry
web_server:
  version: 3
  local: true
  port: 80
  sorting_groups:
    - id: group_content
      name: "Content"
      sorting_weight: 0
    - id: sorting_group_number_settings
      name: "Number settings"
      sorting_weight: 20

switch:
  - platform: gpio
    pin: GPIO26
    id: motor_power
    name: "Motor Power"

uart: # The SFD Modules are sitting together on UART and only work with this settings.
  - id: uart_bus
    tx_pin: 17
    rx_pin: 16
    baud_rate: 4800
    parity: EVEN
    stop_bits: 2

sfd_vosloh:
  id: sfd
  uart_id: uart_bus
  row_length: 25
  last_module: 75
  current_content:
    name: content
    web_server:
      sorting_group_id: group_content
  # current_c_state:
  #   name: char state
  # current_m_state:
  #   name: motor state
  rolling:
    name: rolling
    on_press:
      then:
        - switch.turn_on: motor_power
    on_release:
      then:
        - switch.turn_off: motor_power

time:
  - id: my_time
    platform: sntp
    timezone: Europe/Berlin

    on_time:
      - seconds: 0
        minutes: /1
        then:
          - sfdVosloh.content:
              id: sfd
              text: !lambda |-
                return id(my_time).now().strftime("%d.%m.%Y %H:%M");
              align: center
              row: 2
    on_time_sync:
      then:
        - sfdVosloh.content:
            id: sfd
            text: !lambda |-
              return id(my_time).now().strftime("%d.%m.%Y %H:%M");
            align: center
            row: 2
  
text:
  - platform: template
    id: _test
    name: "Test"
    mode: text
    optimistic: true
    web_server:
      sorting_group_id: group_content
    on_value:
      then:
        - sfdVosloh.content:
            id: sfd
            text: !lambda |-
              return x.c_str();
            align: center
            word_wrap: true

select:
  - platform: template
    id: _text
    name: "Text"
    optimistic: true
    web_server:
      sorting_group_id: group_content
    options:
      - ""
      - "Dieser Text dient zum test der Anzeige.\n Der Zeilenumbruch sollte auch funktionieren."
      - "Dies ist ein Text zum testen der Anzeige. \nDer Zeilenumbruch sollte auch funktionieren."
      - "Dies ist ein Text zum testen der Anzeige; \n Der Zeilenumbruch sollte auch funktionieren."
    on_value:
      then:
        - sfdVosloh.content:
            id: sfd
            text: !lambda |-
              return x.c_str();
            align: right
            word_wrap: true

button:
  - platform: restart
    name: "Restart"

  - platform: template
    name: "go blank"
    on_press:
      - sfdVosloh.clear:
          id: sfd

  - platform: template
    name: "roll up"
    on_press:
      - sfdVosloh.roll:
          id: sfd

  - platform: template
    id: show_time
    name: "show time"
    web_server:
      sorting_group_id: group_content
    on_press:
      - sfdVosloh.content:
          id: sfd
          text: !lambda |-
            return id(my_time).now().strftime("%d.%m.%Y %H:%M");
          align: center
          row: 2